extern crate libc;
extern crate libz_sys;

// The bindings generated by bindgen
mod generated { include!(concat!(env!("OUT_DIR"), "/jsapi.rs")); }

// The jsglue module just implements traits so can be private
mod jsglue;

// Modules with public definitions
pub mod rooting;
pub mod jsval;

// Reexport the bindings in the jsapi module
pub use generated::root as jsapi;
